name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Run self on README
        run: |
          pip install -r requirements.txt
          python find_broken.py https://raw.githubusercontent.com/{{github.repo}}/master/README.md
